.travis.yml
Travis CI does not appear to be working, see https://travis-ci.com/ruby/logger/jobs/164283690
The issue seems to be when running the test suite with `bundle exec rake test`. For now, we should run CI with just `rake test`.
=> Dont run bundle exec rake when running tests in CI

.travis.yml, logger.gemspec
I can't think of a reason why Bundler needs to be locked to specifically `1.16.0`, we should be ok to use any version that the user has installed. (hopefully 🤞)
=> Dont lock bundler to a specific version

logger.gemspec
The gemspec is specifying files like `.travis.yml` and `.gitignore` to be included in gem releases, which i don't think is required. 
This PR removes these files from the `files` entry in the gemspec
=> Remove files that dont need to be included in gem releases

logger.gemspec
Since it uses `&.`, it can't be used on older rubies
=> Say that logger requires ruby >= 2.3

lib/logger.rb, test/logger/test_severity.rb
This is a proposal to make it easier for 3rd party implementations to support same interface without depending on `Logger` constants.
Rather than writing `logger.level = Logger::DEBUG`, we can write `logger.debug!`. I believe this is better since it is aligned with the "Ask, don't tell" software design pattern.
=> Add support for changing severity using bang methods.

README.md
Fix https://github.com/ruby/logger/issues/21.
The `test-unit` gem has `--location` option, but the customized test-unit like library on this repo did not have the option.
I want to use `test-unit` gem instead of the library on this repo, but it will be done somedays (PR is welcome)
=> Fix testing example to use --name option

lib/logger.rb
Is there any reason not to do this?
=> Enable `frozen_string_literal: true` in `logger.rb`.

.travis.yml
Removes an old setting from Travis. See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
=> CI: Drop unused setting

lib/logger/log_device.rb, test/logger/test_logdevice.rb
This should allow reopen to work.  Requested in ruby issue #14595.
=> Set filename when initializing logger with a File object

lib/logger.rb, lib/logger/log_device.rb, test/logger/test_logdevice.rb, test/logger/test_logger.rb
Without binmode strings with incompatible encoding can't be written in
the file. This is very common in applications that log user provided
parameters.
We need to allow changing the binnary mode because right now it is impossible to use
the built-in log rotation feature when you provide a File object to the
LogDevice, and if you provide a filename you can't have binmode.
=> Add option to set the binary mode of the log device

lib/logger/formatter.rb
This patch reduces object allocations when logging an Exception that has no backtrace.
=> Avoid creating [] and "" when logging an Exception that has no backtrace

test/lib/core_assertions.rb, test/lib/envutil.rb, test/logger/helper.rb, test/logger/test_logdevice.rb, test/logger/test_logger.rb, test/logger/test_severity.rb
This pull request further updates from https://github.com/ruby/logger/pull/32.
1. Backport from https://github.com/ruby/ruby/blob/master/tool/lib/test/unit/core_assertions.rb. and update the some of workarounds for default gems.
2. Resolve inconsistency directory structure from ruby core repository for `helper.rb`
=> Backport test library from ruby core directly.

lib/logger.rb, test/logger/test_logger.rb
We attempt to override `Logger#level` in Rails’s Logger subclass to [allow setting a different level per thread](https://github.com/rails/rails/blob/d03d6fc33b4e9629e3e969c18bda4bdcd3c01c90/activesupport/lib/active_support/logger_thread_safe_level.rb) (and thus per request). But `Logger#add` checks the new message’s severity against the `@level` instance variable, so overriding `#level` doesn’t have the intended effect. (We also prepend a check against `#level` to `#add`, so you can only set the thread-local level greater than or equal to `@level`, not less. We’d like to allow setting any thread-local level.)
This patch modifies `Logger#add` to check `#level` so that third-party loggers can customize how the current level is determined without needing to reimplement `#add` or juggle …
=> Honor Logger#level overrides

lib/logger/period.rb, test/logger/test_logdevice.rb
Consider 'now' and 'everytime' as valid values for the previous behavior of rotating every time.
Fixes Ruby Bug 15977
=> Raise ArgumentError for invalid shift_age

test/logger/test_logdevice.rb
I recently updated `test/ruby/test_time_tz.rb` to enable the related tests on OpenBSD (as they all pass).  All of logger's tests pass with this enabled on OpenBSD.
=> Enable more timezone tests on OpenBSD

lib/logger.rb
=> Document that shift_age of 0 disables log file rotation

logger.gemspec, test/logger/helper.rb, test/logger/test_logdevice.rb
I found the missing commits on http://github.com/ruby/ruby
=> Backport ruby core changes

lib/logger.rb, test/logger/test_logger.rb
References erroneous upstream PR https://github.com/ruby/ruby/pull/2989
I noticed on a `Logger` instance with `File::NULL` or `/dev/null` as log device arguments a lot of formatting and other overhead still occurs, with the expected result essentially still being "I want to blackhole these logs":
```
GC: 130 (7.40%)
==================================
TOTAL    (pct)     SAMPLES    (pct)     FRAME
348  (19.8%)         348  (19.8%)     Logger::Formatter#format_datetime
614  (35.0%)         169   (9.6%)     Logger::Formatter#call
395  (22.5%)         152   (8.7%)     Logger::LogDevice#write
```
The logger was configured as `Logger.new(File::NULL)`.
=> Let File::NULL ("/dev/null", "NUL" etc.) be considered a nil log device

lib/logger.rb
We can make a logger that does nothing by `Logger.new(nil)`, but it is not documented.
This pull request adds a mention of the behavior.
=> Mention behavior when logdev is a nil in the document

lib/logger/log_device.rb, test/logger/test_logdevice.rb
This should fix Ruby Bug 12468 (https://bugs.ruby-lang.org/issues/12468)
=> Consider cygwin a Windows platform

lib/logger.rb
iff means if and only if, but readers without that knowledge might assume this to be a spelling mistake. To me, this seems like exclusionary language that is unnecessary. Simply using "if and only if" instead should suffice.
Logger changes from https://github.com/ruby/ruby/pull/4035. I had originally issued the patch on ruby/ruby to fix this in the docs. I assume making the change here will find its way into the docs for future releases.
=> Replace "iff" with "if and only if"

.github/workflows/test.yml
=> Drop to support old ruby

logger.gemspec
This gem exposes 0 executables, so we can remove the configuration for that
=> gemspec: Drop unused "executables" configuration

lib/logger/formatter.rb, test/logger/test_formatter.rb, test/logger/test_logger.rb
Formatting a datetime should only pertain to itself and valid datetimes do not contain a space. Should there be a desire to show show a space between the datetime and the process pid in the formatted log, this formatting logic should take place there.
Furthermore, the default datetime format is moved to a class variable to allowing this variable to be overwritten by subclasses.
=> Changes to datetime formatting

lib/logger.rb, lib/logger/log_device.rb, test/lib/core_assertions.rb, test/logger/test_logdevice.rb
Issue only occurs in JRuby 9.3.0.0 and Windows and the full
console output is:
log rotation inter-process lock failed. D:\log.txt -> D:\log.txt.0: The process cannot access the file because it is being used by another process.
log writing failed. closed stream
log writing failed. closed stream
...
=> Fix log rotation inter-process lock failed.

lib/logger/formatter.rb
Here's a tiny performance improvement that suppresses an extra Array object creation on the Logger::Formatter per each `call`.
Just in case anyone needs a benchmark, here's a micro benchmark/ips result on `String#[0..0]` vs `String#[0, 1]`.
```ruby
require 'benchmark/ips'
Benchmark.ips do |x|
string = 'debug'
x.report('[0..0]') { string[0..0] }
x.report('[0, 1]') { string[0, 1] }
x.compare!
end
```
```
Warming up --------------------------------------
[0..0]     1.013M i/100ms
[0, 1]     1.097M i/100ms
Calculating -------------------------------------
[0..0]     10.145M (± 0.7%) i/s -     51.666M in   5.093090s
[0, 1]     10.946M (± 0.7%) i/s -     54.835M in   5.009652s
Comparison:
[0, 1]: 10946494.4 i/s
[0..0]: 10144924.5 i/s - 1.08x  (± 0.00) slower
```
=> Perf improvement on Logger::Formatter#call

lib/logger.rb
This covers the methods and accessors, along with further changes and reorgs in the class doc itself.
=> [DOC] Enhanced RDoc for Logger

lib/logger.rb
Fix https://github.com/ruby/logger/issues/78
=> Fix the Logger::Formatter documentation

lib/logger/formatter.rb
`String#%` takes the arguments as an Array object, which requires us to create an extra object (like we're doing [here](https://github.com/ruby/logger/blob/cafbc353ab4cf0bcf871830f21cce8b5288071b6/lib/logger/formatter.rb#L16-L17)).
Also, while both `String#%` and `Kernel#sprintf` internally falls back `rb_str_format` in the current CRuby implementation, the former seems to be performing a little bit of argument checking, which possibly causes a very subtle performance difference (?).
Anyway, here's a benchmark of `String#%` vs `Kernel#sprintf`.
```ruby
require 'benchmark/ips'
Benchmark.ips do |x|
Format = "%s, [%s #%d] %5s -- %s: %s\n"
DatetimeFormat = "%Y-%m-%dT%H:%M:%S.%6N"
time = Time.now.strftime(DatetimeFormat)
pid = Process.pid
x.report('String#%') { Format % ['D', time, pid, …
```
=> Another performance improvement on the Formatter by using Kernel#sprintf over String#%

CHANGELOG.md, lib/logger.rb, lib/logger/severity.rb, test/logger/test_severity.rb
This adds Logger#with_level which provides a thread-local log level so Threads can temporarily enable logging for a given block.
```ruby
log = Logger.new
log.level = :info
Thread.new do
log.with_level(:debug) do
log.debug("Will log")
end
end.join
log.debug("Won't log")
```
Fixes #84
=> Add thread-local log level

.github/workflows/test.yml
Ruby 2.5 didn't work with `macos-latest`
=> Exclude Ruby 2.5 from macos-latest

lib/logger.rb, lib/logger/log_device.rb, test/logger/test_logger.rb
This allows the user to specify exception classes to treat as regular
exceptions instead of being swallowed.  Among other things, it is
useful for having Logger work with Timeout when having Timeout raise
a specific subclass.
Fixes Ruby Bug 9115. https://bugs.ruby-lang.org/issues/9115
=> Add reraise_exception_classes keyword argument to Logger and LogDevice

lib/logger.rb
Some Ruby apps subclass Logger without running the superclass constructor, which means that `@level_override` isn't initialized properly. This can be fixed in some cases, but the gem should maintain backwards compatibility.
My repro is from using [Chef v12](https://github.com/chef/chef/blob/v12.22.6/lib/chef/monologger.rb), but this should also address #99.
=> Guarantee level_override exists

lib/logger.rb, test/logger/test_severity.rb
`Logger#with_level` was recently added to enable configuring a `Logger`'s level for the duration of a block. However, the configured level is always tied to the currently running `Fiber`, which is not always ideal in applications that mix `Thread`s and `Fiber`s.
For example, Active Support has provided a similar feature (`ActiveSupport::Logger#log_at`) which, depending on configuration, can be isolated to either `Thread`s or `Fiber`s.
This commit enables subclasses of `Logger` to customize the level isolation. Ideally, it will enable replacing most of Active Support's `#log_at`, since both methods end up serving the same purpose.
=> Enable subclasses to configure level isolation

logger.gemspec
So that supply chain tools that look for licenses in the gem can find them, for example https://github.com/github/licensed/pull/765/commits/ff8a5187176d3515cd5afd42ed77db5f043abfd1 (the commit comment there is inaccurate, substitute `logger.gemspec` for `Rakefile`) and so that people distributing the gem automatically comply with the licenses which require copies of the licenses.
=> include license texts in gem

lib/logger/log_device.rb, test/logger/test_logdevice.rb
Since ruby 2.3, a file opened with `File::SHARE_DELETE` and `File::BINARY` can be renamed or removed.
=> Enable log file rotation on Windows

lib/logger/log_device.rb
`/dev/null` is not available on wasm.
=> Use `__FILE__` for wasm

logger.gemspec
By providing a 'changelog_uri' in the metadata of the gemspec a 'Changelog' link will be shown on https://rubygems.org/gems/logger which makes it quick and easy for someone to check on the changes introduced with a new version.
Details of this functionality can be found on https://guides.rubygems.org/specification-reference/#metadata
=> Provide a 'Changelog' link on rubygems.org/gems/logger

logger.gemspec, test/logger/test_logdevice.rb
for https://github.com/ruby/ruby/pull/12537
=> Support to become bundled gems

lib/logger/log_device.rb
Fix logger on TruffleRuby.
TruffleRuby is missing a `File::SHARE_DELETE` constant that is in logger since #102. It was fixed in the TruffleRuby trunk and will be released in the next version.
This proposed temporary workaround in logger is needed to make it work on the current TruffleRuby release.
TruffleRuby issue https://github.com/oracle/truffleruby/issues/3745
=> Add workaround for TruffleRuby and do not use File::SHARE_DELETE

lib/logger/log_device.rb, test/logger/test_logdevice.rb
Because the `path` keyword in File.new will only accept objects that have `to_str`.
The issue I reported in https://github.com/ruby/logger/issues/107#issuecomment-2558300295 will be fixed.
=> Accept the object that has #to_path in Logger::LogDevice.new

lib/logger.rb, lib/logger/log_device.rb, test/logger/test_logdevice.rb
This addresses the issue I raised in #55 
The code in this PR allows setting parameters applicable to a log file in `LogDevice#reopen` as well as during initialization.
I only added the one test to demonstrate the functionality; please let me know what all you would like done here. Should I just copy/paste all of the applicable tests while replacing the constructor code with [these 2 lines](https://github.com/ruby/logger/compare/master...titusfortner:reopen_shifts?expand=1#diff-2509e01a96e40294a3547b0049c17f7cf40614c3a9e91dbf8cabf3edca3c1defR205-R206)? Should I put it in a separate test file?
=> allow setting shift variables in LogDevice when using reopen

lib/logger/log_device.rb
Convert the given file name by the dedicated method, and re-use the converted name instead of the given argument.
=> Refine conversion to path name

lib/logger.rb, test/logger/test_logger.rb
Warn wrong code, https://github.com/ruby/logger/pull/100:
> Some Ruby apps subclass Logger without running the superclass constructor, which means that `@level_override` isn't initialized properly.
=> Subclasses `initialize` must call super

lib/logger.rb, lib/logger/log_device.rb, test/logger/test_logdevice.rb
Creating a logger automatically writes a hardcoded header comment ("# Logfile created on ...").
While this helps verify that logdev is writable as early as possible (rather than on the first log entry), it also serves as a useful indicator of which program created the logfile.
However, this header can introduce unnecessary
complexity -- especially when working with third-party tools that need to ignore these lines.
This commit introduces a `skip_header` boolean
option (default is `false`), allowing API consumers to disable the header if needed.
issue: https://bugs.ruby-lang.org/issues/21133
=> [Feature #21133] Add `skip_header` option

lib/logger.rb, test/logger/test_logger.rb
The motivation here is to fix a Rails issue caused by the way ActiveSupport [extends the ruby Logger][1] to add broadcasting of messages to multiple destinations. I believe the problem could be much more elegantly solved if Logger exposed the underlying LogDevice. Going by repo history, the existence of this object hasn't changed since 2003, so I think it's stable enough to expose.
In addition to letting you read the logdev, this also lets you pass a logdev in. To implement broadcasting, we could now define a LogDevice subclass that delegates its 3 methods to the LogDevices of a list of underlying loggers, and simply create a new logger with this device.
What do you think?
[1]: https://github.com/rails/rails/blob/ba19dbc49956a73f417abd68c7a5f33e302eacd3/activesupport/lib/active_support/log …
=> Expose the logdev
